FROM golang:1.23-alpine AS builder

WORKDIR /app

# installer gcc si package nécessitent cgo (rare)
# RUN apk add --no-cache build-base

COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Binaire statique compatible scratch
RUN CGO_ENABLED=0 GOOS=linux go build -o liste ./cmd/server

FROM scratch
WORKDIR /app
COPY --from=builder /app/liste .

EXPOSE 8080
ENTRYPOINT ["./liste"]
